apiVersion: v1
kind: Service
metadata:
  name: jobservice
spec:
  ports:
    - port: 80
  selector:
    name: jobservice-apps
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: harbor-jobservice-config
data:
  config: |
    appname = jobservice
    runmode = dev
    [dev]
    httpport = {{ .Values.jobservice.port }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jobs-log-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  selector:
    matchLabels:
      type: log
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: jobservice
  labels:
    name: jobservice
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: jobservice-apps
    spec:
      containers:
      - name: jobservice-app
        image: vmware/harbor-jobservice:v1.2.0
        imagePullPolicy: IfNotPresent
        env:
          - name: UI_SECRET
            value: {{ .Values.ui.secret | quote }}
          - name: JOBSERVICE_SECRET
            value: {{ .Values.jobservice.secret | quote }}
          - name: CONFIG_PATH
            value: "/etc/jobservice/app.conf"
          - name: LOG_LEVEL
            value: "debug"
          - name: GODEBUG
            value: "netdns=cgo"
        ports:
        - containerPort: {{ .Values.jobservice.port }}
        volumeMounts:
        - name: config
          mountPath: /etc/jobservice
        - name: logs
          mountPath: /var/log/jobs
      volumes:
      - name: config
        configMap:
          name: harbor-jobservice-config
          items:
          - key: config
            path: app.conf
      - name: logs
        persistentVolumeClaim:
          claimName: jobs-log-pvc 
