apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: registry-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  selector:
    matchLabels:
      type: registry
---
apiVersion: v1
kind: Service
metadata:
  name: registry
spec:
  ports:
    - name: repo
      port: 5000
    - name: debug
      port: 5001
  selector:
    name: registry-apps
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: registry
  labels:
    name: registry
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: registry-apps
    spec:
      containers:
      - name: registry-app
        image: vmware/registry:2.6.2-photon
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
        - containerPort: 5001
        volumeMounts:
        - name: config
          mountPath: /etc/registry
        - name: storage
          mountPath: /storage
      volumes:
      - name: config
        configMap:
          name: harbor-registry-config
          items:
          - key: config
            path: config.yml
          - key: cert
            path: root.crt
      - name: storage
        persistentVolumeClaim:
          claimName: registry-pvc
